const nameList = [
    'Aarav', 'Vivaan', 'Ananya', 'Ishaan', 'Riya',
    'Aditya', 'Kiara', 'Arjun', 'Tara', 'Krishna',
    'Saanvi', 'Aryan', 'Meera', 'Kavya', 'Vihaan',
    'Lakshmi', 'Rohan', 'Naina', 'Dev', 'Priya',
    'Avni', 'Rudra', 'Kiran', 'Dhruv', 'Aditi',
    'Manish', 'Neha', 'Siddharth', 'Sita', 'Rahul',
    'Arpita', 'Rakesh', 'Pooja', 'Kartik', 'Sneha',
    'Mohan', 'Vandana', 'Suresh', 'Anjali', 'Nikhil',
    'Geeta', 'Ashok', 'Rekha', 'Abhay', 'Alok',
    'Bharat', 'Chitra', 'Gaurav', 'Harsh', 'Indira',
    'Jay', 'Leela', 'Maya', 'Naveen', 'Omkar',
    'Parvati', 'Raj', 'Sonia', 'Tejas', 'Vikas',
    'James', 'Emma', 'Liam', 'Olivia', 'William',
    'Sophia', 'Benjamin', 'Isabella', 'Michael', 'Mia',
    'Elijah', 'Charlotte', 'Lucas', 'Amelia', 'Mason',
    'Harper', 'Ethan', 'Evelyn', 'Jacob', 'Ava',
    'Alexander', 'Scarlett', 'Henry', 'Emily', 'Daniel',
    'Elizabeth', 'Matthew', 'Madison', 'Jackson', 'Lily',
    'Aiden', 'Ella', 'Samuel', 'Aria', 'Joseph',
    'Abigail', 'John', 'Avery', 'David', 'Sofia',
    'Christopher', 'Chloe', 'Andrew', 'Grace', 'Joshua',
    'Zoey', 'Carter', 'Lillian', 'Nathan', 'Victoria',
    'Logan', 'Hannah', 'Owen', 'Addison', 'Dylan',
    'Brooklyn', 'Sebastian', 'Natalie', 'Levi', 'Savannah'
];

export function generateRandomnames() {
    return nameList[Math.floor(Math.random() * nameList.length)];
};


const messageList = [
    "Amazing video!",
    "Incredible effort!",
    "Loved the vibe.",
    "So creative!",
    "Absolutely stunning.",
    "Next level 🔥",
    "Keep it up!",
    "Pure talent.",
    "You nailed it!",
    "Outstanding work.",
    "Legendary move!",
    "Super inspiring.",
    "This is gold.",
    "Perfection!",
    "Unbelievably cool.",
    "Such positive energy 💚",
    "Brilliant execution!",
    "Keep shining!",
    "Wow, just wow!",
    "Very well done.",
    "Art at its finest.",
    "Mind-blowing!",
    "Big fan of this!",
    "Iconic.",
    "🔥 Amazing video!",
    "💚 Love this!",
    "Wow, this is incredible! ✨",
    "💥 Mind-blowing!",
    "This made my day! 😊",
    "Epic content! 🙌",
    "🔥💯 Absolutely nailed it!",
    "Such a vibe! 🎶",
    "👏 Incredible work!",
    "💚 So inspiring!",
    "This is next level! 🚀",
    "Perfection! 🌟",
    "Can't stop watching this! 🔥",
    "Legendary! 🏆",
    "Wow! You’re so talented! 🤩",
    "I’m speechless… ✨",
    "More of this, please! 🔥",
    "💥 Totally hooked!",
    "This deserves all the hype! 👏",
    "Simply amazing! 💯🔥",
    "💚 This is gold!",
    "Unreal talent right here! 💥",
    "🔥 Too good to be true!",
    "Such wholesome vibes! 💚😊",
    "Speechless… WOW! 💯",
    "So much love for this! 💚✨",
    "This hit different. 🔥💯",
    "Never seen anything like this before! 🙌",
    "Effortless class.",
    "The best I've seen today.",
    "This deserves all the praise.",
    "So unique!",
    "Way to go!",
    "Amazing creativity 🔥",
    "Love the details 💚",
    "Beautifully done.",
    "Exceptional work.",
    "Incredible visuals!",
    "Made my day!",
    "Wow, the effort shows.",
    "Top-tier quality.",
    "This is so cool.",
    "Keep creating!",
    "Simply fantastic.",
    "I'm speechless!",
    "This is epic.",
    "Jaw-dropping!",
    "Nothing short of amazing."
];

export function generateRandomMessage() {
    return messageList[Math.floor(Math.random() * messageList.length)];
}
